// Design tokens as CSS custom properties (ADR 0009). `renderTokensCss()`
// writes src/styles/tokens.css (run `npm run tokens`); `schemeVars()` is what
// lib/theme.ts sets at runtime for a user's accent. Both come from here, so the
// static file and the runtime values can't drift (m3.test.ts checks the file).
import { hexToRgb } from './color';
import { DEFAULT_SEED, ROLES, schemeFor, type Scheme, type SchemeTheme } from './scheme';

/** --md-sys-color-<role> (hex) and --md-sys-color-<role>-rgb ("r g b", for Tailwind alpha). */
export function schemeVars(scheme: Scheme): Record<string, string> {
  const out: Record<string, string> = {};
  for (const role of ROLES) {
    out[`--md-sys-color-${role}`] = scheme[role];
    out[`--md-sys-color-${role}-rgb`] = hexToRgb(scheme[role]).join(' ');
  }
  return out;
}

// M3 type scale: [size px, line-height px, weight, tracking px]. Sizes are
// emitted in rem off a 16px base; the app's root is 17px, so everything reads
// ~6% larger than stock M3 ("easier to read than a typical ERP").
export const TYPE_SCALE = {
  'display-large': [57, 64, 400, -0.25], 'display-medium': [45, 52, 400, 0], 'display-small': [36, 44, 400, 0],
  'headline-large': [32, 40, 400, 0], 'headline-medium': [28, 36, 400, 0], 'headline-small': [24, 32, 400, 0],
  'title-large': [22, 28, 500, 0], 'title-medium': [16, 24, 500, 0.15], 'title-small': [14, 20, 500, 0.1],
  'body-large': [16, 24, 400, 0.5], 'body-medium': [14, 20, 400, 0.25], 'body-small': [12, 16, 400, 0.4],
  'label-large': [14, 20, 500, 0.1], 'label-medium': [12, 16, 500, 0.5], 'label-small': [11, 16, 500, 0.5],
} as const;
export type TypeRole = keyof typeof TYPE_SCALE;

export const SHAPE = {
  none: '0px', 'extra-small': '4px', small: '8px', medium: '12px', large: '16px', 'extra-large': '28px', full: '9999px',
} as const;

const K = 'rgb(0 0 0 / 0.3)', A = 'rgb(0 0 0 / 0.15)';
export const ELEVATION = [
  'none',
  `0 1px 2px 0 ${K}, 0 1px 3px 1px ${A}`,
  `0 1px 2px 0 ${K}, 0 2px 6px 2px ${A}`,
  `0 1px 3px 0 ${K}, 0 4px 8px 3px ${A}`,
  `0 2px 3px 0 ${K}, 0 6px 10px 4px ${A}`,
  `0 4px 4px 0 ${K}, 0 8px 12px 6px ${A}`,
] as const;

export const STATE_OPACITY = { hover: 0.08, focus: 0.1, pressed: 0.1, dragged: 0.16 } as const;

// Old token names (pre-M3 pages: bg-bg, text-ink, border-line …) mapped onto
// scheme roles so un-migrated pages follow the theme. Page builders replace
// these with role classes; delete once nothing uses them.
export const LEGACY_ALIASES: Record<string, string> = {
  bg: 'surface-container-low', surface: 'surface', ink: 'on-surface', muted: 'on-surface-variant',
  line: 'outline-variant', accent: 'primary', 'accent-contrast': 'on-primary',
  warn: 'warning', danger: 'error', ok: 'success',
};

const px = (n: number) => `${+(n / 16).toFixed(4)}rem`;
const block = (sel: string, vars: Record<string, string>) =>
  `${sel} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}\n`;

function staticVars(): Record<string, string> {
  const v: Record<string, string> = {};
  for (const [role, [size, lh, weight, track]] of Object.entries(TYPE_SCALE)) {
    const p = `--md-sys-typescale-${role}`;
    v[`${p}-size`] = px(size); v[`${p}-line-height`] = px(lh);
    v[`${p}-weight`] = String(weight); v[`${p}-tracking`] = `${track}px`;
  }
  for (const [k, val] of Object.entries(SHAPE)) v[`--md-sys-shape-corner-${k}`] = val;
  ELEVATION.forEach((s, i) => { v[`--md-sys-elevation-level${i}`] = s; });
  for (const [k, val] of Object.entries(STATE_OPACITY)) v[`--md-sys-state-${k}-state-layer-opacity`] = String(val);
  for (const [k, role] of Object.entries(LEGACY_ALIASES)) v[`--${k}`] = `var(--md-sys-color-${role})`;
  v['--radius'] = 'var(--md-sys-shape-corner-small)';
  return v;
}

const THEME_SELECTORS: [SchemeTheme, string][] = [
  ['light', ":root,\n[data-theme='light']"],
  ['dark', "[data-theme='dark']"],
  ['minimal', "[data-theme='minimal']"],
];

export function renderTokensCss(seed = DEFAULT_SEED): string {
  const head = `/* GENERATED by \`npm run tokens\` from src/lib/m3 (seed ${seed}). Do not edit by hand.\n` +
    ` * Material 3 design tokens (ADR 0009). A user's accent overrides the color\n * roles at runtime (src/lib/theme.ts). */\n\n`;
  return head + block(':root', staticVars()) + '\n' +
    THEME_SELECTORS.map(([t, sel]) => block(sel, schemeVars(schemeFor(seed, t)))).join('\n');
}
